apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: ha-postgres
  namespace: database
spec:
  instances: 3
  imageName: ghcr.io/cloudnative-pg/postgresql:16.4

  affinity:
    enablePodAntiAffinity: true
    topologyKey: "topology.kubernetes.io/zone"

  resources:
    requests:
      memory: "512Mi"
      cpu: "250m"
    limits:
      memory: "1Gi"
      cpu: "1000m"

  storage:
    size: "1Gi"

  backup:
    retentionPolicy: "30d"
    barmanObjectStore:
      destinationPath: "gs://devops-portfolio-backups/postgres"
      googleCredentials:
        gkeEnvironment: true
      wal:
        compression: gzip
