apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: ollama-scaler
  namespace: ai-inference
spec:
  scaleTargetRef:
    name: ollama
  minReplicaCount: 0
  maxReplicaCount: 1
  cooldownPeriod: 60
  pollingInterval: 10
  triggers:
    - type: redis
      metadata:
        address: redis.ai-inference.svc.cluster.local:6379
        listName: inference_processing
        listLength: "5"
        activationListLength: "0"
