apiVersion: apps/v1
kind: Deployment
metadata:
    name: redis-cart
    namespace: boutique
    labels:
        app: redis-cart
        app.kubernetes.io/part-of: online-boutique
        consize.dev/iac-source: kubernetes-yaml
        consize.dev/container: redis
spec:
    selector:
        matchLabels:
            app: redis-cart
    template:
        metadata:
            labels:
                app: redis-cart
        spec:
            securityContext:
                fsGroup: 1000
                runAsGroup: 1000
                runAsNonRoot: true
                runAsUser: 1000
            containers:
                - name: redis
                  image: redis:alpine
                  ports:
                    - containerPort: 6379
                  livenessProbe:
                    periodSeconds: 5
                    tcpSocket:
                        port: 6379
                  readinessProbe:
                    periodSeconds: 5
                    tcpSocket:
                        port: 6379
                  resources:
                    requests:
                        cpu: 21m
                        memory: 140Mi
                    limits:
                        cpu: 42m
                        memory: 179Mi
                  securityContext:
                    allowPrivilegeEscalation: false
                    capabilities:
                        drop:
                            - ALL
                    privileged: false
                    readOnlyRootFilesystem: true
                  volumeMounts:
                    - mountPath: /data
                      name: redis-data
            volumes:
                - name: redis-data
                  emptyDir: {}
